### DISCUSSION TITLE
Doctrine cannot update database

### DISCUSSION THREAD

**Discussion by arsrobota** [doctrine/doctrine2#10779] [Support Questions]
### Doctrine version(s) affected

2.5.12

### Description

I'm working on a massive project with five databases; Since it is a rewriting I had to start from existing (very very badly designed) databases and generate their entities using reverse engineering. This project was created in Symfony 7.4 then upgraded to 6.2.11, using Rector to convertannotations to attributes.

After upgrading I created a basic controller. In one of this controller's method I receive a form in order to update an entity. I receive data from the request, I can fetch the entity and udate it, but database is not updated and no exception is raised.  I also tried creating a brand new entity instance and it works, new data are persisted in database; moreover I can successfully update this newly created entity.
I checked Symfony profiler, the entity is well mapped, connections and entity manager are OK.

I suspected troubles with PHP attributes (perhaps missing or incorrect ones) but not quite sure of it. Then I thought about Doctrine misconfiguration but as there is not problem reading databases, I'm not sure either.

Does anybody have a clue of what is going wrong ?
Thanks a lot for any help.

Alex

EDIT: I really suspect a problem with the fact that generated annotations have been converted to attributes. I'm adding rector config.

### How to reproduce

```
composer.json
{
  "type": "project",
  "license": "proprietary",
  "version": "6.2.0",
  "minimum-stability": "stable",
  "prefer-stable": true,
  "repositories": [
    {
      "type": "composer",
      "url": "https://repos.tech.orange/artifactory/api/composer/php-proxy-official"
    },
    {
      "type": "composer",
      "url": "https://repos.tech.orange/artifactory/api/composer/ccphp-epo-virt-composer-stable"
    },
    {
      "packagist": false
    }
  ],
  "require": {
    "php": ">=8.1",
    "ext-ctype": "*",
    "ext-iconv": "*",
    "doctrine/doctrine-bundle": "^2.9",
    "doctrine/doctrine-migrations-bundle": "^3.2",
    "doctrine/orm": "^2.15",
    "epo/auth-sso-bundle": "^6.0",
    "epo/menu-bundle": "^6.0",
    "epo/security-bundle": "^6.0",
    "epo/theme-boosted-ui-bundle": "^6.0",
    "epo/theme-bootstrap-ui-bundle": "^6.2",
    "epo/user-entity-bundle": "^6.0",
    "symfony/cache": "6.2.*",
    "symfony/console": "6.2.*",
    "symfony/dotenv": "6.2.*",
    "symfony/flex": "^1.17 | ^2.0",
    "symfony/form": "6.2.*",
    "symfony/framework-bundle": "6.2.*",
    "symfony/runtime": "6.2.*",
    "symfony/translation": "6.2.*",
    "symfony/webpack-encore-bundle": "^1.16",
    "symfony/yaml": "6.2.*"
  },
  "require-dev": {
    "epo/installer": "^2.0",
    "rector/rector": "^0.17.0",
    "symfony/debug-bundle": "6.2.*",
    "symfony/maker-bundle": "^1.48",
    "symfony/stopwatch": "6.2.*",
    "symfony/web-profiler-bundle": "6.2.*"
  },
  "config": {
    "allow-plugins": {
      "composer/package-versions-deprecated": true,
      "symfony/flex": true,
      "epo/installer": true,
      "symfony/runtime": true
    },
    "bin-dir": "bin",
    "optimize-autoloader": true,
    "preferred-install": {
      "*": "dist"
    },
    "sort-packages": true
  },
  "autoload": {
    "psr-4": {
      "App\\": "src/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "App\\Tests\\": "tests/"
    }
  },
  "replace": {
    "paragonie/random_compat": "2.*",
    "symfony/polyfill-ctype": "*",
    "symfony/polyfill-iconv": "*",
    "symfony/polyfill-php72": "*",
    "symfony/polyfill-php71": "*",
    "symfony/polyfill-php70": "*",
    "symfony/polyfill-php56": "*"
  },
  "scripts": {
    "auto-scripts": {
      "cache:clear": "symfony-cmd",
      "assets:install %PUBLIC_DIR%": "symfony-cmd"
    },
    "post-install-cmd": [
      "@auto-scripts"
    ],
    "post-update-cmd": [
      "@auto-scripts"
    ]
  },
  "conflict": {
    "doctrine/doctrine-bundle": ">3.0",
    "symfony/symfony": "*",
    "symfony/cache": ">=7.0",
    "symfony/config": ">=7.0",
    "symfony/dependency-injection": ">=7.0",
    "symfony/error-handler": ">=7.0",
    "symfony/event-dispatcher": ">=7.0",
    "symfony/filesystem": ">=7.0",
    "symfony/finder": ">=7.0",
    "symfony/form": ">=7.0.0",
    "symfony/http-foundation": ">=7.0",
    "symfony/http-kernel": ">=7.0",
    "symfony/mime": ">=7.0",
    "symfony/options-resolver": ">=7.0",
    "symfony/password-hasher": ">=7.0",
    "symfony/property-access": ">=7.0",
    "symfony/property-info": ">=7.0",
    "symfony/routing": ">=7.0",
    "symfony/security-csrf": ">=7.0",
    "symfony/stopwatch": ">=7.0",
    "symfony/string": ">=7.0",
    "symfony/twig-bridge": ">=7.0",
    "symfony/twig-bundle": ">=7.0",
    "symfony/validator": ">=7.0",
    "symfony/var-dumper": ">=7.0",
    "symfony/var-exporter": ">=7.0",
    "symfony/web-profiler-bundle": ">=7.0"
  },
  "extra": {
    "symfony": {
      "require": "6.2.*",
      "allow-contrib": true,
      "endpoint": [
        "flex://defaults"
      ]
    }
  }
}
```

```
# doctrine.yaml

doctrine:
    dbal:
        default_connection: dummy
        connections:
            dummy:
                url: '%env(resolve:DUMMY_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.6.5'
            fire:
                url: '%env(resolve:FIRE_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.6.5'
                charset: 'utf8mb4'
                default_table_options:
                    charset: 'utf8mb4'
                    collate: 'utf8mb4_general_ci'

                schema_filter: ~.*[^_to_del]$~
                # options: 1001: true is PDO::MYSQL_ATTR_LOCAL_INFILE implementation (necessary to use LOAD DATA LOCAL INFILE)
                options:
                    1001: true
            leclair:
                url: '%env(resolve:LECLAIR_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.6.5'
                charset: 'utf8mb4'
                default_table_options:
                    charset: 'utf8mb4'
                    collate: 'utf8mb4_general_ci'

                schema_filter: ~.*[^_to_del]$~
                options:
                    1001: true
            leclair_vad:
                url: '%env(resolve:LECLAIR_VAD_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.6.5'
                charset: 'utf8mb4'
                default_table_options:
                    charset: 'utf8mb4'
                    collate: 'utf8mb4_general_ci'

                schema_filter: ~.*[^_to_del]$~
                options:
                    1001: true
            leclair_int:
                url: '%env(resolve:LECLAIR_INT_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.6.5'
                charset: 'utf8mb4'
                default_table_options:
                    charset: 'utf8mb4'
                    collate: 'utf8mb4_general_ci'

                schema_filter: ~.*[^_to_del]$~
                options:
                    1001: true
            leclair_mobi:
                url: '%env(resolve:LECLAIR_MOBI_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.6.5'
                charset: 'utf8mb4'
                default_table_options:
                    charset: 'utf8mb4'
                    collate: 'utf8mb4_general_ci'

                schema_filter: ~.*[^_to_del]$~
                options:
                    1001: true
    orm:
        default_entity_manager: dummy
        auto_generate_proxy_classes: true
        entity_managers:
            dummy:
                connection: dummy
                mappings:
                    Dummy:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Dummy
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
            fire:
                connection: fire
                mappings:
                    Fire:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Fire'
                        prefix: 'App\Entity\Fire'
                        alias: Fire
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
            leclair:
                connection: leclair
                mappings:
                    Leclair:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Leclair'
                        prefix: 'App\Entity\Leclair'
                        alias: Leclair
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
            leclair_vad:
                connection: leclair_vad
                mappings:
                    LeclairVad:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/LeclairVad'
                        prefix: 'App\Entity\LeclairVad'
                        alias: LeclairVad
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
            leclair_int:
                connection: leclair_int
                mappings:
                    LeclairInt:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/LeclairInt'
                        prefix: 'App\Entity\LeclairInt'
                        alias: LeclairInt
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
            leclair_mobi:
                connection: leclair_mobi
                mappings:
                    LeclairMobi:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/LeclairMobi'
                        prefix: 'App\Entity\LeclairMobi'
                        alias: LeclairMobi
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
```

```
// DefinitionCritere.php

<?php
declare(strict_types=1);

namespace App\Entity\Leclair;

use App\Repository\Leclair\DefinitionCritereRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * DefinitionCritere
 *
 */
#[ORM\Table(name: 'definition_critere', schema: 'leclair')]
#[ORM\Entity(repositoryClass: DefinitionCritereRepository::class)]
class DefinitionCritere
{
    /**
     * @var int
     *
     */
    #[ORM\Column(name: 'num_critere', type: 'integer', nullable: false)]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    private $numCritere;

    #[ORM\Column(name: 'nom_critere', type: 'string', length: 200, nullable: false)]
    private string $nomCritere = '';

    #[ORM\Column(name: 'type_retour', type: 'string', length: 100, nullable: false)]
    private string $typeRetour = '';

    #[ORM\Column(name: 'description', type: 'string', length: 500, nullable: true)]
    private ?string $description = null;

    /**
     * @var \DateTime|null
     *
     */
    #[ORM\Column(name: 'date_crea', type: 'datetime', nullable: true)]
    private ?\DateTimeInterface $dateCrea = null;

    /**
     * @var \DateTime|null
     *
     */
    #[ORM\Column(name: 'date_last_modif', type: 'datetime', nullable: true)]
    private ?\DateTimeInterface $dateLastModif = null;

    #[ORM\Column(name: 'user', type: 'string', length: 12, nullable: true)]
    private ?string $user = null;

    #[ORM\Column(name: 'requete_critere', type: 'text', length: 0, nullable: false)]
    private ?string $requeteCritere = null;

    /**
     * @var int
     *
     */
    #[ORM\Column(name: 'ordre_affichage', type: 'integer', nullable: false)]
    private $ordreAffichage = '0';

    /**
     * @var int
     *
     */
    #[ORM\Column(name: 'num_critere_histo', type: 'integer', nullable: false)]
    private $numCritereHisto = '0';

    public function getNumCritere(): ?int
    {
        return $this->numCritere;
    }

    public function getNomCritere(): ?string
    {
        return $this->nomCritere;
    }

    public function setNomCritere(string $nomCritere): self
    {
        $this->nomCritere = $nomCritere;

        return $this;
    }

    public function getTypeRetour(): ?string
    {
        return $this->typeRetour;
    }

    public function setTypeRetour(string $typeRetour): self
    {
        $this->typeRetour = $typeRetour;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateCrea(): ?\DateTimeInterface
    {
        return $this->dateCrea;
    }

    public function setDateCrea(?\DateTimeInterface $dateCrea): self
    {
        $this->dateCrea = $dateCrea;

        return $this;
    }

    public function getDateLastModif(): ?\DateTimeInterface
    {
        return $this->dateLastModif;
    }

    public function setDateLastModif(?\DateTimeInterface $dateLastModif): self
    {
        $this->dateLastModif = $dateLastModif;

        return $this;
    }

    public function getUser(): ?string
    {
        return $this->user;
    }

    public function setUser(?string $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getRequeteCritere(): ?string
    {
        return $this->requeteCritere;
    }

    public function setRequeteCritere(string $requeteCritere): self
    {
        $this->requeteCritere = $requeteCritere;

        return $this;
    }

    public function getOrdreAffichage(): ?int
    {
        return $this->ordreAffichage;
    }

    public function setOrdreAffichage(int $ordreAffichage): self
    {
        $this->ordreAffichage = $ordreAffichage;

        return $this;
    }

    public function getNumCritereHisto(): ?int
    {
        return $this->numCritereHisto;
    }

    public function setNumCritereHisto(int $numCritereHisto): self
    {
        $this->numCritereHisto = $numCritereHisto;

        return $this;
    }
}
```

```
// CriteriaController.php

#[Route(path: '/modifier', name: 'edit')]
    public function edit(Request $request, EntityManagerInterface $em): Response
    {
        if ( ! $this->isCsrfTokenValid('edit_query_', $request->request->get('_edit_token'))) {
            return new Response('CSRF token is not valid', Response::HTTP_BAD_REQUEST);
        }

        $query = $em->getRepository(DefinitionCritere::class)->findOneBy(['numCritere' => $request->request->get('queryId')]);
        $query->setRequeteCritere($request->request->get('editQuery'));

        $em->flush();

        $this->addFlash('success', 'La requête a bien été modifiée.');

        return $this->redirectToRoute('administration_rules_criteria_index');
    }
```

```
// rector.php
<?php

declare(strict_types=1);

use Rector\CodeQuality\Rector\Class_\InlineConstructorDefaultToPropertyRector;
use Rector\Config\RectorConfig;
use Rector\Doctrine\Set\DoctrineSetList;
use Rector\Set\ValueObject\LevelSetList;
use Rector\Set\ValueObject\SetList;
use Rector\Symfony\Set\SensiolabsSetList;
use Rector\Symfony\Set\SymfonyLevelSetList;
use Rector\Symfony\Set\SymfonySetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/config',
        __DIR__ . '/public',
        __DIR__ . '/src',
    ]);

    // register a single rule
    $rectorConfig->rule(InlineConstructorDefaultToPropertyRector::class);

    // define sets of rules
    $rectorConfig->sets([
        LevelSetList::UP_TO_PHP_81,
        SetList::CODE_QUALITY,
        DoctrineSetList::ANNOTATIONS_TO_ATTRIBUTES,
        SymfonySetList::ANNOTATIONS_TO_ATTRIBUTES,
        SensiolabsSetList::FRAMEWORK_EXTRA_61,
        SymfonyLevelSetList::UP_TO_SYMFONY_62,
        SymfonySetList::SYMFONY_CONSTRUCTOR_INJECTION
    ]);
};
```
