### DISCUSSION TITLE
Cannot load fixtures with entity references using AliceBundle after Doctrine ORM 2.16+

### DISCUSSION THREAD

**Discussion by Cyanat** [doctrine/doctrine2#11918] [Support Questions]
Hello!
I'm using `Hautelook\AliceBundle` to load my fixtures. Currently, with `doctrine/orm 2.9.6`, here's an example of how my fixtures look:

**category.yml:**
```
App\Entity\Category:
    category_news:
        __construct: [news]
        position: 1
        readOnly: true
```
**channel.yml:**
```
App\Entity\Channel:
    channel_1:
        num: 1
        name: CNN
        type: tv
        isEnabled: 1
        category: '<category(news)>'
```
`<category(news)>` refers to a data fixture provider in my app that returns the entity reference.
This setup allows me to:
- Case 1: Load all fixture files on a clean database — works perfectly.
- Case 2: Load only `channel.yml` on an instance where categories are already stored — also works fine.

However, after upgrading to `doctrine/orm 2.20.2` (the issue seems to appear starting from 2.16.0, after ticket #10785), trying to load all fixtures (Case 1) now results in the following error:
```
In UnitOfWork.php line 1637:
                                                                               
  [RuntimeException]                                                           
  While adding an entity of class App\Entity\Category with an ID hash of "new  
  s" to the identity map,                                                      
  another object of class Proxies\__CG__\App\Entity\Category was already pres  
  ent for the same ID. This exception                                          
  is a safeguard against an internal inconsistency - IDs should uniquely map   
  to                                                                           
  entity object instances. This problem may occur if:                          
                                                                               
  - you use application-provided IDs and reuse ID values;                      
  - database-provided IDs are reassigned after truncating the database withou  
  t                                                                            
    clearing the EntityManager;                                                
  - you might have been using EntityManager#getReference() to create a refere  
  nce                                                                          
    for a nonexistent ID that was subsequently (by the RDBMS) assigned to ano  
  ther                                                                         
    entity.                                                                    
                                                                               
  Otherwise, it might be an ORM-internal inconsistency, please report it.      
                                                                               

Exception trace:
  at /application/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1637
...
```

I've worked around the issue by updating the `channel.yml` fixture like this:
```
App\Entity\Channel:
    channel_1:
        num: 1
        name: CNN
        type: tv
        isEnabled: 1
        category: '@category_news'
```

This solves the problem when loading everything at once.
But it breaks my ability to load only `channel.yml` (Case 2).

So this upgrade introduces a regression in my use case.

Is my previous usage incorrect?
Or is there a recommended practice that would allow me to continue loading fixtures in both scenarios?

Thanks in advance!
