### DISCUSSION TITLE
The class «Entity» was not found in the chain configured namespaces in production mode

### DISCUSSION THREAD

**Discussion by marcelkorpel** [doctrine/doctrine2#8687] [Support Questions] [answered]
For a project I use separate databases and entity managers using Symfony 5.2.7 and Doctrine ORM 2.8.2. My `doctrine.yaml` looks like
```yaml
doctrine:
    dbal:
        connections:
            myproject:
                driver: 'pdo_mysql'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                override_url: true
                url: '%env(resolve:DATABASE_URL_MYPROJECT)%'
    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            myproject:
                connection: myproject
                mappings:
                    MyProject:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/MyProject'
                        prefix: 'App\Entity\MyProject'
                        alias: MyProject
```
(only one database and entity manager is currently used, but this is to be extended in the future).

When I try to get the repository class of an entity within a controller using 
```php
        $repository = $this->getDoctrine()->getRepository(Entity::class);
```
everything is fine, regardless of in which mode Symfony runs.

However, when trying to get that class from an autowired entity manager within a generic (service) class, like
```php
class Service
{
    private ObjectRepository $repository;

    public function __construct(EntityManagerInterface $em)
    {
        $this->repository = $em->getRepository(Entity::class);
    }
    /* … */
}
```
Symfony outputs a 500 error **when running in production mode** and writes
```
request.CRITICAL: Uncaught PHP Exception Doctrine\Persistence\Mapping\MappingException: "The class 'App\Entity\MyProject\Entity' was not found in the chain configured namespaces " at /srv/http/myproject/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/MappingException.php line 23 {"exception":"[object] (Doctrine\\Persistence\\Mapping\\MappingException(code: 0): The class 'App\\Entity\\MyProject\\Entity' was not found in the chain configured namespaces  at /srv/http/myproject/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/MappingException.php:23)"}
```
to `/srv/http/myproject/var/log/prod.log`.

For the record, the service class is also autowired in the controller method:
```php
class TheController extends AbstractController
{
    /* … */
    public function router(string $path, Service $service): Response
    /* … */
}
```
Everything works as expected, no error is thrown or output in `dev.log`, when `APP_ENV=dev`.

**Comment by beberlei** [comment]
This is not technically a Doctrine problem, because these kinds of object wiring happens in Symfony. I moved it to a support question for now.

**Reply by marcelkorpel** [reply]
With some more searching on the internet after creating a [minimal example](https://github.com/marcelkorpel/symfony-autowiring-bug) for a [Symfony issue](https://github.com/symfony/symfony/issues/41226), I now think it's still a Doctrine bug: when I change the name of the entity manager in `config/packages/doctrine.yaml` and in `config/packages/doctrine_migrations.yaml` to `default`, everything works fine in production mode. I *suspect* the autowiring error comes in at a later stage, as this minimal example doesn't output it.

Moreover, I can think that I missed a `doctrine.orm.default_entity_manager` property, but setting that one to `myproject` doesn't solve this issue, only creating an entity manager named `default` does. So, why does Doctrine need a default entity manager to be called `default` and why does this error not pop up with `APP_ENV=dev`?

**Reply by beberlei** [reply]
There is a setting `default_entity_manager: default` in Doctrine Bundle. You can change that. Why it doesn't happen in dev I don't know and requires knowledge of Symfony and DoctrineBundle interaction that I don't posses.

**Reply by marcelkorpel** [reply]
But that was just my point, I think I wan't totally clear: when I set `default_entity_manager: myproject`, I still get a 500 error in production mode. The entity manager **has** to be called `default`.

**Comment by ostrolucky** [comment, marked as answer]
You are probably running into https://github.com/doctrine/DoctrineBundle/issues/1337.  Make sure you define  `entity_managers:` config in your prod/doctrine.yaml

**Reply by marcelkorpel** [reply]
Indeed. I copied the `entity_managers` to prod/doctrine.yaml, and I had to remove the default options `metadata_cache_driver`, `query_cache_driver`, and `result_cache_driver`, because those were not recognized, and now everything works as expected.

I suppose when https://github.com/doctrine/DoctrineBundle/issues/1337 is solved, I can revert prod/doctrine.yaml back to the default settings, again?

**Reply by ostrolucky** [reply]
We will probably "solve it" in a way that we will prevent having these mixed configurations in files, so you either have to define entity_managers in both files, or in none of them. So no.

**Reply by yapro** [reply]
Починил так: добавил в doctrine.yaml параметр default_entity_manager: entity_manager_mysql
было:
```
when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
```
стало:
```
when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            default_entity_manager: entity_manager_mysql
```
где entity_manager_mysql это значение из значения выше, полная версия файла doctrine.yaml
```
doctrine:
    dbal:
        default_connection: connection_mysql
        connections:
            connection_mysql:
                wrapper_class: YaPro\DoctrineExt\Wrapping\DBALConnectionWrapper
                host:     '%env(MYSQL_HOST)%'
                port:     '%env(MYSQL_PORT)%'
                dbname:   '%env(MYSQL_DATABASE)%'
                user:     '%env(MYSQL_USERNAME)%'
                password: '%env(MYSQL_PASSWORD)%'
                driver: 'pdo_mysql'
                server_version: '5'
                # игнорируем таблицы начинающиеся с префикса monolog https://symfony.com/bundles/DoctrineMigrationsBundle/current/index.html#manual-tables
                schema_filter: ~^(?!monolog)~
                # для нескольких таблиц попробовать: ~^(?!(monolog|sessions))~
                # альтернатива: app/console doctrine:migrations:diff --filter-expression=/^prefix_/

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: entity_manager_mysql
        entity_managers:
            entity_manager_mysql:
                naming_strategy: doctrine.orm.naming_strategy.default
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'

# закомментировал, т.к. при следующей настройке теряется определение всех выше указанных параметров для doctrine.dbal:
# when@test:
#     doctrine:
#         dbal:
#             # "TEST_TOKEN" is typically set by ParaTest
#             dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
            # данный параметр приходится дублировать из-за ошибки https://github.com/doctrine/orm/discussions/8687
            default_entity_manager: entity_manager_mysql

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    # cache.app - используется для кэша в собственном коде:
                    adapter: cache.app
                    # bin/console debug:config framework - говорит, что исользуется сервис: cache.adapter.filesystem
                doctrine.system_cache_pool:
                    # cache.system - системный кеш используется для таких вещей, как аннотации, сериализатор и валидация:
                    adapter: cache.system
                    # bin/console debug:config framework - говорит, что исользуется сервис: cache.adapter.system он
                    # создается с помощью \Symfony\Component\Cache\Adapter\AbstractAdapter::createSystemCache и является
                    # Symfony\Component\Cache\Adapter\PhpFilesAdapter-ом или ApcuAdapter-ом если ApcuAdapter::isSupported()
```
