### DISCUSSION TITLE
Combining PHP 8 attributes with old style annotations

### DISCUSSION THREAD

**Discussion by jelovac** [doctrine/doctrine2#8925] [Support Questions]
Can we combine attributes and old style annotations when working with entities which belong to the same namespace? I am involved in refactoring and migrating some legacy codebase to Symfony 5 and would like to gradually replace the old style annotations in entities with PHP 8 attributes.

According to some discussion on StackOverflow in order to enable PHP 8 Attributes support in Symfony 5 we had to change the mapping type from "annotation" to "attribute" like in the example below:

```
# config/packages/doctrine.yaml

doctrine:
  orm:
    mappings:
        App:
            type: attribute
```

So according to the above example will old style annotations be ignored or parsed as well?
