### ISSUE TITLE
It is not possible to disable the second level cache programmatically

### ISSUE THREAD

**Issue by kov-lucas** [doctrine/doctrine2#10670]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no -> _don't know what this is_
| Version     | 2.14.3

#### Summary
It is not possible to disable the second level cache programmatically.

#### Current behavior
The second level cache is enabled on doctrine.yaml, but when I try to disable it programmatically it ignores the settings and keeps caching entities and queries.

#### How to reproduce
My default settings are below
**doctrine.yaml**
```
                second_level_cache:
                    enabled: true
                    regions:
                        one_hour:
                            lifetime: 3600
                            cache_driver:
                                type: pool
                                pool: second_level_cache_pool
                        one_day:
                            lifetime: 86400
                            cache_driver:
                                type: pool
                                pool: second_level_cache_pool
```

This is the service that I use in case I need to disable the second level cache (eg. User decided to switch off the caching).
**SecondLevelCacheService.php**
```
class SecondLevelCacheService
{
    public const REGIONS = [
        'one_hour' => 3600,
        'one_day' => 86400,
    ];

    public function __construct(
        private ConfigurationService $configurationService,
        private EntityManagerInterface $em,
        private CacheInterface $cache
    ) {
    }

    public function disableSecondLevelCache(): void
    {
        $this->em->getConfiguration()->setsecondLevelCacheEnabled(false);
    }
}
```
Another example, if I remove everything from the doctrine.yaml file and try to enable the second level cache programmatically like this, it also fails and catches nothing.
```
    public function enableSecondLevelCache(): void
    {
        $regionConfig = new RegionsConfiguration();

        foreach (self::REGIONS as $regionName => $regionLifetime) {
            $regionConfig->setLifetime($regionName, $regionLifetime);
            $regions[] = new DefaultRegion($regionName, $this->cache, $regionLifetime);
        }

        $factory = new DefaultCacheFactory(
            $regionConfig,
            $this->cache
        );

        foreach ($regions as $region) {
            $factory->setRegion($region);
        }

        $logger = new CacheLoggerChain();
        $logger->setLogger('statistics', new StatisticsCacheLogger());

        $cacheConfig = new CacheConfiguration();
        $cacheConfig->setCacheFactory($factory);
        $cacheConfig->setRegionsConfiguration($regionConfig);
        $cacheConfig->setCacheLogger($logger);

        $config = new Configuration();
        $config->setSecondLevelCacheEnabled();
        $config->setSecondLevelCacheConfiguration($cacheConfig);

        $this->em->getConfiguration()->setsecondLevelCacheEnabled();
        $this->em->getConfiguration()->setSecondLevelCacheConfiguration($cacheConfig);
    }
```

#### Expected behavior
I can configure the caching programmatically, and override the yaml definition.
