### ISSUE TITLE
EntityListenerPass unaware of ResolveTargetEntityListener::$resolveTargetEntities

### ISSUE THREAD

**Issue by BreyndotEchse** [doctrine/doctrine2#10829]
### Feature Request
|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary
The `Doctrine\ORM\Tools\AttachEntityListenersListener` does not attach any entity listeners targeting interfaces or abstract classes, because it is not aware of the `Doctrine\ORM\Tools\ResolveTargetEntityListener::$resolveTargetEntities` used to resolve and load ClassMetadata of these interfaces or classes.

Dysfunctional config example:
```yaml
# doctrine.yaml
doctrine:
    orm:
        resolve_target_entities:
            FooInterface: Foo
```
```yaml
# services.yaml
services:
    FooListener:
        tags:
            - { name: doctrine.orm.entity_listener, entity: FooInterface }
#                                                              ^- Works only without "Interface" suffix
```
So what I would like to do is:
- Move `ResolveTargetEntityListener::$resolveTargetEntities` to separate service: TargetEntityResolver
- Inject TargetEntityResolver service into ResolveTargetEntityListener and AttachEntityListenersListener
- Forward `ResolveTargetEntityListener::addResolveTargetEntity()` calls to `TargetEntityResolver::addResolveTargetEntity()`
- Add `@deprecated` doc to `ResolveTargetEntityListener::addResolveTargetEntity()`
- Use resolved entities to attach listeners in AttachEntityListenersListener

Any concerns?

(Copied from https://github.com/doctrine/DoctrineBundle/issues/1683)
