### ISSUE TITLE
Calling setAssociationOverride in prePersist/preUpdate throws an exception

### ISSUE THREAD

**Issue by jkabat** [doctrine/doctrine2#11957]
### Bug Report

After upgrade to v3 I'm facing following exception "Typed property Doctrine\ORM\Mapping\ClassMetadata::$namingStrategy must not be accessed before initialization"

It might be caused by the fact naming strategy service is removed in compiler pass?

|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                  | 3.3.2
| Previous working version     | 2.20.2

**Comment by jkabat** [comment]
During debugging I've found out removal of following config resolves the issue

```yaml
    doctrine:
        orm:
            metadata_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
```

I will do more tests, but in the past I had to keep the setting for one of my bundles.

@ostrolucky could it be a problem with DoctrineBundle?
Also removing metadata_cache_driver can lead to performance degradation?
