### ISSUE TITLE
DDC-1605: No documentation about the usage of indexes with YAML and XML

### ISSUE THREAD

**Issue by doctrinebot** [doctrine/doctrine2#2244]
Jira issue originally created by user naitsirch:

I am missing documentation about how to handle indexes in YAML and XML definition files. I had to search in the code to learn how to do that.
Please add some documentation about it.

This issue is related to #[DDC-160](http://www.doctrine-project.org/jira/browse/DDC-160) where the reporter asked for documentation about indexes in annotation mapping.

EDIT:
Maybe an example how I have done it with YAML would be helpful for others:

```
User:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: IDENTITY
    email:
      type: string
      length: 150
      unique: true
    active:
      type: boolean
  indexes:
    indexActiveField: { name: idx*user*active, columns: [ active ] }
```

`indexActiveField` is the name of the index used by doctrine and `idx*user*active` is the name of the index in the database. The rest should be clear.
