### ISSUE TITLE
DDC-3277: Yaml convert-mapping bug

### ISSUE THREAD

**Issue by doctrinebot** [doctrine/doctrine2#4067]
Jira issue originally created by user Kilrogg:

I use yaml mapping in my project for better migration management. For example, I use 

```
    orm:convert-mapping yml ./yml --from-database --namespace="User\Entity\\" --filter="User\Entity\User"
```

To make yml entites for my User module. In my yml I have smth like this:

```
      password:
            type: string
            nullable: false
            length: 256
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: ''
        status:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
```

I can write a comment to column

```
         status:
                type: smallint
                nullable: true
                unsigned: false
                comment: '%some comment%'
                column: status
```

And when I perform migration comment disappears.  Here https://github.com/doctrine/migrations/issues/184 I was adviced to use such construction:

```
    status:
        type: smallint
        nullable: true
        column: status
        options:
            unsigned: false
            comment: '%some comment%'
```

And It works! But convert-mapping generates wrong code. Does anyone know any way to generate a correct one with convert-mapping?
