### ISSUE TITLE
DDC-3284: Yaml mapping. Comment on table and realtion

### ISSUE THREAD

**Issue by doctrinebot** [doctrine/doctrine2#4075]
Jira issue originally created by user Kilrogg:

Is there any way to comment my tables and table relations with yml schema?
I can comment plain field like this

```
        prediction:
            type: text
            nullable: true
            length: null
            fixed: false
            options:                
                comment: 'program prediction'
```

But for relation:

```
        project:
            targetEntity: File\Entity\File
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                project:
                    referencedColumnName: id
            orphanRemoval: false
            options:                
                comment: 'File with project data'
```

Or for whole table:

```
Program\Entity\Program:
    type: entity
    table: program
    options:
        comment: 'State program table'
```

It  doesn't work at all. When I perform migrations those comments are totally ignored. And I can't find any documentation for yml mapping table commenting
