### ISSUE TITLE
DDC-3360: Problem custom name sequeceGenerator YAML for annotatition entities

### ISSUE THREAD

**Issue by doctrinebot** [doctrine/doctrine2#4160]
Jira issue originally created by user sandrocandido:

Hi Benjamin

Problem custom name sequeceGenerator YAML why not create the custom name you want. Being created the default postgres, where is the problem?

Note:  https://groups.google.com/forum/#!topic/doctrine-user/7ctTFGWu4mo

Message:

```
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: SEQUENCE
      sequenceGenerator:
        sequenceName: message_sq
        allocationSize: 100
        initialValue: 1
```

The entity is created like this:

```
namespace message\models\entities;

use Doctrine\ORM\Mapping as ORM;

/****
 * Message
 *
 * @ORM\Table(name="message")
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 */
class Message
{
    /****
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\SequenceGenerator(sequenceName="message*id*seq", allocationSize=1, initialValue=1)
     */
```

Should be created as specify:

```
/****
 * Message
 *
 * @ORM\Table(name="message")
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 */
class Message
{
    /****
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\SequenceGenerator(sequenceName="message_sq", allocationSize=1, initialValue=1)
     */
```
