### ISSUE TITLE
DDC-3711: Error on manyToMany with composite primary key

### ISSUE THREAD

**Issue by doctrinebot** [doctrine/doctrine2#4547]
Jira issue originally created by user pantelm:

Hi,
I hope that I report in the right place.
I have an issue when I try to create an manyToMany association with an entity with a composite primary key.
The problem is that only one of the two key are create on the association table.

I also have manyToOne association that works fine.

Here are the mapping

`Commune.orm.yml`

```
AppDemo\ZoneBundle\Entity\Commune:
    type: entity
    table: ref_commune
    id:
        codeInsee:
            type: string
            nullable: false
            length: 5
            fixed: true
            column: commune*code*insee
        codePostal:
            type: string
            nullable: false
            length: 5
            fixed: true
            column: commune*code*postal
    fields:
        nom:
            type: string
            nullable: false
            length: 100
            fixed: false
            column: commune_nom
    manyToMany:
        zones:
            targetEntity: Zone
            joinTable:
                name: lnk*zone*commune
                joinColumns:
                    commune*code*insee:
                        referencedColumnName: commune*code*insee
                    commune*code*postal:
                        referencedColumnName: commune*code*postal
                inverseJoinColumns:
                    zone_id:
                        referencedColumnName: zone_idx
```

`Zone.orm.yml`

```
AppDemo\ZoneBundle\Entity\Zone:
    type: entity
    repositoryClass: AppDemo\ZoneBundle\Repository\ZoneRepository
    table: ref_zone
    id:
        idx:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: zone_idx
            generator:
                strategy: IDENTITY
    fields:
        libelle:
            type: string
            nullable: false
            length: 30
            options:
                default: ''
                comment: 'Libelle de la Zone'
```
