### ISSUE TITLE
DDC-3718: Inifinite schema diff when using decimal with options unsigned

### ISSUE THREAD

**Issue by doctrinebot** [doctrine/doctrine2#4554]
Jira issue originally created by user kminh:

When using a mapping similar to:

```
        field_name:
            type: decimal
            scale: 2
            options:
                unsigned: true
```

I keep getting this when issuing `app/console doctrine:schema:update --dump-sql` (symfony console):

```
ALTER TABLE table*name CHANGE field_name field*name NUMERIC(10, 2) NOT NULL;
```

could be related to: http://www.doctrine-project.org/jira/browse/DC-752
