### ISSUE TITLE
DDC-3852: [GH-1479] Quoted field - yaml driver

### ISSUE THREAD

**Issue by doctrinebot** [doctrine/doctrine2#4703]
Jira issue originally created by user @doctrinebot:

This issue is created automatically through a Github pull request on behalf of bigfoot90:

Url: https://github.com/doctrine/doctrine2/pull/1479

Message:

Allow the usage of `quoted` field mapping option in yaml mappings

Example:

```
MyModel:
    type: entity
    fields:
        values:
            type: string
            quoted: true
```
