### ISSUE TITLE
IdentifierFlattener breaks on custom object typed ids

### ISSUE THREAD

**Issue by hcomnetworkers** [doctrine/doctrine2#5631]
We use a custom Uuid type object in a closure table tree. When trying to get the ancestors or descendants this error is thrown:

> 'Notice: Undefined index: id' in /vendor/doctrine/orm/lib/Doctrine/ORM/Utility/IdentifierFlattener.php on line 98

It appears the `is_object($id[$field])` in `IdentifierFlattener::flattenIdentifier` is insufficient to distinquish a real entity from our Uuid-Object. When I exclude our Uuid there via an instanceof check, everything works as expected.

```yaml
Node:
  type: entity
  id:
    id:
      type: UuidType
      id: true
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: xxx\Doctrine\ORM\Id\UuidGenerator
...
```
```yaml
Closure:
  type: entity
  id:
    ancestor:
      id: true
      associationKey: true
      column: ancestor
    descendant:
      id: true
      associationKey: true
      column: descendant
  manyToOne:
    ancestor:
      targetEntity: Node
      inversedBy: descendants
      joinColumns:
        ancestor:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
    descendant:
      targetEntity: Node
      inversedBy: ancestors
      joinColumns:
        descendant:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
```

E.g. this throws the notice and breaks the code, when $uuid is one of our UuidType-Objects:
```php
$ancestors = $closureRepository->findBy(['descendant' => $uuid]);
```

This seems related to the closed tickets https://github.com/doctrine/doctrine2/pull/1336 and https://github.com/doctrine/doctrine2/issues/4448.
