### ISSUE TITLE
[Mssql 2012] Create entity for view

### ISSUE THREAD

**Issue by Slavenin** [doctrine/doctrine2#5751]
Hello!
I created view in my db and orm file for it. 

```yml
Entity\Mssql\Myview:
    type: entity
    table: MyView
    readOnly: true
    id:
        id:
            type: guid
            nullable: false
            length: null
            fixed: false
            id: true
            column: Id
    fields:
        name:
            type: string
            nullable: false
            length: 1024
            fixed: false
            column: Name
        entity:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: entity
```
but when i run 
```bash
php app/console doctrine:schema:update --dump-sql
```
generated sql query for create this table. Problem in vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php in getListTablesSQL and getListTableColumnsSQL in this function select object with type 'U' this phisycal table, view has type = 'V'. This class also has getListViewsSQL method, but i can not find where it using. How i can say doctrine that my entity is view?
