### ISSUE TITLE
Problem custom name sequeceGenerator YAML for annotatition entities

### ISSUE THREAD

**Issue by monstrodopantano** [doctrine/doctrine2#5789]
Problem custom name sequeceGenerator YAML why not create the custom name you want. Being created the default postgres, where is the problem?

``` yml
Message:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: SEQUENCE
      sequenceGenerator:
        **sequenceName: message_sq**
        allocationSize: 100
        initialValue: 1
```

The entity is created like this:
use Doctrine\ORM\Mapping as ORM;

``` php
/**
 * Message
 *
 * @ORM\Table(name="message")
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 */
class Message
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\SequenceGenerator(**sequenceName="message_id_seq"**, allocationSize=1, initialValue=1)
     */
```

Should be created as specify:

``` php
/**
 * Message
 *
 * @ORM\Table(name="message")
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 */
class Message
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\SequenceGenerator(**sequenceName="message_sq",** allocationSize=1, initialValue=1)
     */
```
