### ISSUE TITLE
Embeddable in mapped superclass

### ISSUE THREAD

**Issue by uirapuru** [doctrine/doctrine2#6078]
Hi! I got three classes: a super class with mapping, an extending it class and embedded value object.

Mapping for superclass:

```
Occurrence:
  type: mappedSuperclass
  table: occurrences
  embedded:
    duration:
      class: Duration
      columnPrefix: false
```

Mapping for embeddable:

```
Duration:
  type:   embeddable
  fields:
    minutes:
      type: integer
      nullable: true
```

Just for sake of a test I created extending class that inherits everything from Occurrence class:

```
/**
 * Class Occurrence
 * @ORM\Entity()
 * @ORM\Table(name="occurrences")
 */
class Occurrence extends BaseOccurrence
{
}
```

Schema is being created correctly with `minutes` column in database, fixtures are being loaded correctly, but:

 - column `minutes` value after persisting an object is the only one always empty (only this value is not saved), despite that value in `$occurrence->duration()->minutes()` is set.
 - after getting data from DB and hydrating object everything is fine except that `$occurrence->duration()` is always `NULL`.

What I'm doing wrong? please help! :) (Or my wife will kill me, I didn't slept in my bed today because of that error).
