### ISSUE TITLE
Update transactions and concurrency documentation with example of YAML versioning column

### ISSUE THREAD

**Issue by clubery** [doctrine/doctrine2#6137]
Currently on http://doctrine-orm.readthedocs.io/en/latest/reference/transactions-and-concurrency.html#optimistic-locking there is no example of how to setup a versioning column for an entity using YAML config like the following:

```
Allocation:
    type: entity
    table: allocations
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: AUTO
    fields:
        expiry:
            type: datetime
            nullable: true
            column: expiry
        created:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
        version:
            type: integer
            version:
                type: integer
                default: 1
```

Took me hours to locate the solution as obvious as it may seem and credit goes to this guy: http://stackoverflow.com/questions/31693136/doctrine2-version-annotation-in-yaml-file
