### ISSUE TITLE
Column not quoted in ManyToOne relation 

### ISSUE THREAD

**Issue by andynador** [doctrine/doctrine2#6202]
In Postgres I have tables `firm` with field `firmId` and `card` with field `firmId`. When I try to write relation and load related data, I got error - `column firmid  does not exist`. Looks like related column not quoted in SQL-query. Could anyone help, how I can fix problem? Definition on relations:
```
  Cards:
...
    manyToOne:
      firm:
        targetEntity: Firms
        inversedBy: cards
        joinColumn:
          name: "`firmId`"
          referencedColumnName: "`firmId`"
...
Firms:
    id:
        firmId:
            type: bigint
            column: "`firmId`"
...
    oneToMany:
      cards:
        targetEntity: Cards
        mappedBy: firm
...
```
