### ISSUE TITLE
Automatically apply a custom sql-function on a property inside an entity

### ISSUE THREAD

**Issue by mutale** [doctrine/doctrine2#6269]
Enable to wrap entity property (database value of field) with a custom sql-function (that's known by dql),

Use case:
Translating a value when get data with findAll().

Suggestion:
Wrapping the term value with sql function in select fields.

Example:
config.yml:
```
orm:
    mappings:
      AppBundle:
        type: annotation
    dql:
      string_functions:
        translate_term: AppBundle\DoctrineExtensions\Utils\TranslateTerm
```

Entity:
```
 /**
     * @var string
     *
     * @ORM\Column(name="mi_term", type="string", length=25, nullable=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomWrapper(class="AppBundle\DoctrineExtensions\Utils\TranslateTerm")
     */
    private $miTerm;
```
