### ISSUE TITLE
yml association documentation has typing error

### ISSUE THREAD

**Issue by Zebercet** [doctrine/doctrine2#6321]
One-To-Many, Bidirectional documentation is like that:

```
Product:
  type: entity
  oneToMany:
    features:
      targetEntity: Feature
      mappedBy: product
Feature:
  type: entity
  manyToOne:
    product:
      targetEntity: Product
      inversedBy: features
      joinColumn:
        name: product_id
        referencedColumnName: id
```

but association keys have to start with upper case. "oneToMany" has to be "OneToMany"
