### ISSUE TITLE
Persisting entities with cross-schema relationships between multiple entity managers

### ISSUE THREAD

**Issue by brandinchiu** [doctrine/doctrine2#6350]
I am looking for any up-to-date documentation on Doctrine ORM's ability to handle cross-schema relationships between entities.  This currently doesn't appear to be possible, as the entity manager of the persisting entity does not understand the state of entity being managed by the other manager.

This leads to confusing states where an ORMInvalidArgumentException is thrown (due to an unfulfilled cascade), or a MySQL unique constraint fails (Doctrine tries to persist the related entity, but it's clearly already in the DB).

Is there a specific way to handle this via Doctrine config, or is this still an unsupported feature?

Will it _ever_ be a supported feature, or is there an official stance Doctrine has on this use-case?

Thanks!

**Comment by Ocramius** [comment]
Sharing entities across multiple EntityManager instances is not supported,
and will need a separate managed entity copy instead.

**Comment by brandinchiu** [comment]
@Ocramius: could you point me in the direction of how I would accomplish this?

**Comment by Ocramius** [comment]
If you never did this before, you can edit the files directly from the
github UI and send them back for inclusion in our repository.

**Comment by brandinchiu** [comment]
My mistake, I thought this was existent functionality that I just wasn't utilising.  My familiarity with the guts of Doctrine is pretty minimal, and I'm not sure how effective a PR from me would be.  But I'll take a gander and see what I can come up with.

**Comment by Ocramius** [comment]
@brandinchiu you just need to replace that `::class` with a string reference (FQN)

**Comment by brandinchiu** [comment]
I'm afraid I'm not clear on which ::class reference you are referring to.

**Comment by Ocramius** [comment]
@brandinchiu urgh, sorry, totally mixed up. My replies should have gone to a different thread. Sorry! :-(

Backtracking a bit:

 > @Ocramius: could you point me in the direction of how I would accomplish this?

You would need to communicate across the separate entity managers via identifiers only:

```php
$service1->doSomethingOnService2($service2, $someEntity);
```

Would translate to something like:

```php
public function doSomethingOnService2(Service2 $service, SomeEntity $entity)
{
    $service->doSomething($entity->someId());
}
```

**Comment by brandinchiu** [comment]
In this example, are these services entity managers, or my own custom logic running on top of them?  I already have something like this that is managing the entities on my end, the problems I'm running into are at the last leg, when I need the entities persisted.

Fetching objects has been no problem, including the ones with the cross-schema relations.  

I've played around with some changes to the underlying Doctrine code, and I've managed to get as far (in testing) as to prevent the EM1 from trying to cascade-persist the foreign entity from the other schema.

The problem I run into after that is that Entity1, managed by EM1, doesn't maintain the ID from Entity2(foreign)/EM2, even though EM1 knows about the entity.  When it gets to the point where it needs to actually write Entity1, the foreign key is null.  I haven't found an intelligent way to reconcile that yet, mostly because I'm still trying to figure out how Doctrine handles the in-memory storage of foreign entities.

**Comment by Ocramius** [comment]
> The problem I run into after that is that Entity1, managed by EM1, doesn't maintain the ID from Entity2(foreign)/EM2, even though EM1 knows about the entity. When it gets to the point where it needs to actually write Entity1, the foreign key is null. I haven't found an intelligent way to reconcile that yet, mostly because I'm still trying to figure out how Doctrine handles the in-memory storage of foreign entities.

I would need a piece of code that reproduces your issue in isolation to get you to a workaround. Can't help just by imagining what you are doing, sorry...

**Comment by brandinchiu** [comment]
Of course; here's a more concrete example of what I'm attempting to do:

Assume I have 3 schemas:
* data_1
* data_2
* data_index

data_1/2 are application databases storing relevant information for two clients.  It stores user, financial, and other information for those clients.

data_index is an array of enum-like tables, which consist of ID->Name pairs.  These are more or less non-transactional, static values.  Things like roles, types, languages and countries.

My individual database servers will consist of multiple data_n schemas, and _ideally_, *one* data_index schema, shared across them.

The example I am currently working with is persisting new users to a data_n schema, which requires a valid role ID from data_index.role.

What I've attempted to do for testing is to introduce a new cascade option: *ignore*.  I've modified the list of acceptable cascade parameters, and modified the foreach loop in UnitOfWork:735, to not compute association changes if $assoc['isCascadeIgnore'].

This obviously prevents entity manager managing *data_n.user * from trying to persist the role entity from the foreign schema.  However, once the entity manager tries to actually persist the user, it confusingly doesn't know the role ID, even though Entity\User->getRole()->getId() is not null.

Would you like the actual compilation of my changes, or is this enough to suggest a course of action?

**Comment by Ocramius** [comment]
I'm asking for an actual code example.

**Comment by brandinchiu** [comment]
**Entity Metadata**
```yaml
CoreBundle\Entity\User:
    type: entity
    table: user
    indexes:
        FKEY_user_status_id_idx:
            columns:
                - status_id
        FKEY_user_tier_id_idx:
            columns:
                - tier_id
        FKEY_user_role_id_idx:
            columns:
                - role_id
    uniqueConstraints:
        email_UNIQUE:
            columns:
                - email
...
manyToOne:
        role:
            targetEntity: Role
            cascade: [ "ignore" ]
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                role_id:
                    referencedColumnName: id
            orphanRemoval: false
...
```
**\Doctrine\ORM\Mapping\MappingException:776** (added new cascade option to exception message)
```php
return new self(sprintf(
            "You have specified invalid cascade options for %s::$%s: %s; available options: 'remove', 'persist', 'refresh', 'merge', 'detach', and 'ignore'",
            $className,
            $propertyName,
            $cascades
        ));
```

**\Doctrine\ORM\Mapping\ClassMetadataInfo:1517** (added new cascade option to array_intersect and added new mapping index 'isCascadeIgnore')
```php
if (count($cascades) !== count(array_intersect($cascades, array('remove', 'persist', 'refresh', 'merge', 'detach', 'ignore')))) {
            throw MappingException::invalidCascadeOption(
                array_diff($cascades, array_intersect($cascades, array('remove', 'persist', 'refresh', 'merge', 'detach', 'ignore'))),
                $this->name,
                $mapping['fieldName']
            );
        }
...
$mapping['isCascadeIgnore'] = in_array('ignore',  $cascades);
```

**\Doctrine\ORM\UnitOfWork:735** (prevent $this->computeAssociationChanges from running if isCascadeIgnore)
```php
foreach ($class->associationMappings as $field => $assoc) {

            if (($val = $class->reflFields[$field]->getValue($entity)) === null) {
                continue;
            }

            if ($assoc['isCascadeIgnore']){
                continue;
            }
...
}
```

Is this better? Or do you want an actual PR?

**Comment by Ocramius** [comment]
No, I'm asking where you are sharing an entity reference... :-\

**Comment by brandinchiu** [comment]
Like, where I'm instantiating the user entity and then setting the role?

**Comment by Ocramius** [comment]
Yes: without going into ORM internals, how are you using the ORM API? Can you make an example that, using multiple entity managers, reproduces your issue?

**Comment by brandinchiu** [comment]
I'm working with Symfony, and have heavily abstracted out how I work with ORM.  I work with controller classes that wrap around entities to provide functionality.

```php
$user = new Core\Account\UserController();
$user->setEmail('brandinchiu@gmail.com')
    ->setTier(Core\Account\TierController::getDefaultTier())
    ->setRole(Core\Index\RoleController::getRole(Enum\Role::ROLE_USER))
    ->setPassword('plantextpassword')
    ->setFirstName('brandin')
    ->setLastName('chiu')
    ->setBirthdate(new \DateTime(date('Y-m-d', '1991-05-17')))
    ->save()
;
```

UserController::save() basically just runs $em->persist and $em->flush on the wrapped entity.

Core\Index\RoleController::getRole(Enum\Role::ROLE_USER) just returns an instance of RoleController with a preloaded $entity property based on the passed enum.

The UserController->setRole() method takes a RoleController and updates the underlying user entity with that of the RoleController:

 ```php
public function setRole(Core\Index\RoleController $role)
    {
        $this->getEntity()->setRole($role->getEntity());

        return $this;
    }
```

**UserController::__construct()**
```php
    public function __construct($entity = null)
    {
        $this->entityName = $this->getClass();
        $this->entityManager = $this->getContainer()->get('doctrine')->getManager($this->getControllerNamespace());

        /**
         * load the controller from an existing entity;
         * or set properties to null.
         */
        if($entity !== null){
            $this->setEntity($entity);

        } else {
            $this->setEntity($this->nullEntity());
        }
    }
```

UserController::getClass() returns the expected name of the user entity, in this case, _User_.
UserController::getControllerNamespace() returns the expected name of the entity manager, either _'index'_, or _'account'_.
UserController::nullEntity() returns an instance of the entity above, with null properties.
UserController::set<Foo> sets the underlying entity properties.

The result of the topmost section is a UserController, with a ..\Entity\User marked as new by UserController::getEntityManager(), with all the property values that were set above.  If I dump UserController->getEntity()->getRole()->getId, I get the same value as Enum\Role::ROLE_USER.

This is the doctrine config:
```yaml
doctrine:
    dbal:
        default_connection: index
        connections:
            index:
                driver:   pdo_mysql
                host:     "%database_host_index%"
                port:     "%database_port_index%"
                dbname:   "%database_name_index%"
                user:     "%database_user_index%"
                password: "%database_password_index%"
                charset:  UTF8
            account:
                driver:   pdo_mysql
                host:     "%database_host_account%"
                port:     "%database_port_account%"
                dbname:   "%database_name_account%"
                user:     "%database_user_account%"
                password: "%database_password_account%"
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: account
        entity_managers:
            index:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: false
                connection: index
                mappings:
                    CoreBundle:
                        mapping: true
                        type: yml
                        dir: Resources/config/doctrine
                        prefix: CoreBundle\Entity
            account:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                connection: account
                mappings:
                    CoreBundle:
                        mapping: true
                        type: yml
                        dir: Resources/config/doctrine
                        prefix: CoreBundle\Entity
```

I dunno how helpful this is to you ... unless you want me to dump my whole project somewhere for you to swim through ...
