### ISSUE TITLE
[Postgres] Default column value (CURRENT_TIMESTAMP) "date/time value current is no longer supported"

### ISSUE THREAD

**Issue by BabakMN** [doctrine/doctrine2#6383]
This is a preliminary issue I will provide more information if needed.

It seems that the schema tool is wrapping the column default value in single quotes so I get a query like,

```sql
create table test (test timestamptz not null default 'CURRENT_TIMESTAMP');
```

Which causes,

```
[PDOException]                                                                                      
  SQLSTATE[0A000]: Feature not supported: 7 ERROR:  date/time value "current" is no longer supported
```

Column definition:
```yaml
timeCreated:
            column: time_created
            type: datetimetz
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
```

If `CURRENT_TIMESTAMP` is not wrapped in single quotes it will work.

Perhaps `default` is for constant string values and I should use `columnDefinition` instead?
