### ISSUE TITLE
[Bug] SchemaValidator - Sqlite

### ISSUE THREAD

**Issue by benito103e** [doctrine/doctrine2#6445]
Hello,

When using pdo_sqlite driver, if the schema contains Foreign keys (ManyToOne join columns on my case) the schema validator fails : 

> [Database] FAIL - The database schema is not in sync with the current mapping file.

**Comment by Tykzz** [comment]
In my case it's many-to-many relationship and each time I execute `doctrine:schema:update --force ` the output of the dump slightly changes.

Before update:

```sql
DROP INDEX IDX_51A228EEBAD26311; -- <--
DROP INDEX IDX_51A228EE166D1F9C; -- <--
CREATE TEMPORARY TABLE __temp__projects_tags AS SELECT project_id, tag_id FROM projects_tags;
DROP TABLE projects_tags;
CREATE TABLE projects_tags (project_id INTEGER NOT NULL, tag_id INTEGER NOT NULL, PRIMARY KEY(project_id, tag_id), CONSTRAINT FK_51A228EE166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_51A228EEBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO projects_tags (project_id, tag_id) SELECT project_id, tag_id FROM __temp__projects_tags;
DROP TABLE __temp__projects_tags;
CREATE INDEX IDX_51A228EEBAD26311 ON projects_tags (tag_id); -- <--
CREATE INDEX IDX_51A228EE166D1F9C ON projects_tags (project_id); -- <--
```
After update:

```sql
DROP INDEX IDX_51A228EE166D1F9C; -- <--
DROP INDEX IDX_51A228EEBAD26311; -- <--
CREATE TEMPORARY TABLE __temp__projects_tags AS SELECT project_id, tag_id FROM projects_tags;
DROP TABLE projects_tags;
CREATE TABLE projects_tags (project_id INTEGER NOT NULL, tag_id INTEGER NOT NULL, PRIMARY KEY(project_id, tag_id), CONSTRAINT FK_51A228EE166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_51A228EEBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
INSERT INTO projects_tags (project_id, tag_id) SELECT project_id, tag_id FROM __temp__projects_tags;
DROP TABLE __temp__projects_tags;
CREATE INDEX IDX_51A228EE166D1F9C ON projects_tags (project_id); -- <--
CREATE INDEX IDX_51A228EEBAD26311 ON projects_tags (tag_id); -- <--
```

As you can see only the order of dropping and creating indexes has changed.
Does anyone have any idea why is that?

If it helps, here is the mapping:

```yaml
App\Entity\Project:
    type: entity
    table: project
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 100
        description:
            type: text
        source:
            type: string
            length: 200
        demo:
            type: string
            length: 200
    manyToMany:
        tags:
            targetEntity: Tag
            joinTable:
                name: projects_tags
                joinColumns:
                    project_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
```
