### ISSUE TITLE
[Bug] Reference to an entity is lost after selecting a referenced entity separately

### ISSUE THREAD

**Issue by ifif14** [doctrine/doctrine2#6449]
Hello,

I've discovered a following bug today.

I select an entity like so, which has manyToOne relationship to the next entity.

```
$suggest_item =
  Doctrine::em()
  ->getRepository('\DPO\Model\Core\PurchaseOrderItemsSuggest')
  ->findOneBy(
    array(
      'projectid' => $this->projectID,
      'qbpurchaseorderitemsuggestid' => $item->QBItemID
    )
  );

echo ($suggest_item->qbaccount->accountnumber); // echo#1

$accountnumber =
  Doctrine::em()
  ->getRepository('\DPO\Model\Core\AccountNumber')
  ->findOneBy(
    array(
      'projectid' => $this->projectID,
      'qbaccountnumberid' => $item->QBAccountNumberID
    )
  );
echo ($suggest_item->qbaccount->accountnumber); // echo#2
```

When I echo#1 and cause the referenced object to hydrate, everything is okay. 
If I skip the echo#1, then the echo#2 will deliver null.

suggest_item has following relation to account
```
manyToOne:
    qbaccount:
        targetEntity: DPO\Model\Core\AccountNumber
        cascade: {}
        fetch: LAZY
        joinColumns:
            -
                name: ProjectID
                referencedColumnName: ProjectID
            -
                name: QBAccountNumberID
                referencedColumnName: QBAccountNumberID
```
Key of accountnumber looks like follows
```
id:
    qbaccountnumberid:
        type: bigint
        nullable: false
        options:
            unsigned: true
        id: true
        column: QBAccountNumberID
        generator:
            strategy: NONE
    projectid:
        type: bigint
        nullable: false
        options:
            unsigned: true
        id: true
        column: ProjectID
        generator:
            strategy: NONE
```
