### ISSUE TITLE
Second level cache does not support scalar results.

### ISSUE THREAD

**Issue by lcp0578** [doctrine/doctrine2#6627]
```yml
#config.yml

# Doctrine Configuration
doctrine:
  ......
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        # enable metadata caching 
        metadata_cache_driver: redis 
        # enable query caching 
        query_cache_driver: redis 
        filters:
            kit_office_filter: KitBaseBundle\Doctrine\Filter\OfficeFilter
        # enable caching
        second_level_cache:
            region_cache_driver:
                type: service
                id: snc_second_level_cache
            enabled: true
            regions:
                entity_that_rarely_changes:
                    lifetime: 86400
                    cache_driver:
                        type: service
                        id: snc_second_level_cache
```

```php
/**
 * District
 *
 * @ORM\Table(name="district",options={"comment": ""})
 * @ORM\Entity(repositoryClass="KitCaseBundle\Repository\DistrictRepository")
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Cache(usage="NONSTRICT_READ_WRITE", region= "entity_that_rarely_changes")
 */
class District{}

// Repository
public function getChildren($pid, $toArray = false)
    {
        $qb = $this->createQueryBuilder('d');
        $qb->select('d.id,d.name,d.code,d.parentId')
            ->where('d.parentId = :pid AND d.status = :status')
            ->setParameters([
            'pid' => $pid,
            'status' => 1
        ]);
        if ($toArray) {
            return $qb->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        } else {
            return $qb->getQuery()->setCacheable(true)->setCacheRegion('entity_that_rarely_changes')->getResult();
        }
    }
```

What's wrong ?

thanks
