### ISSUE TITLE
Versioned entity with composite id with foreign key can't be updated separately

### ISSUE THREAD

**Issue by etki** [doctrine/doctrine2#6768]
Hi! I'm hitting a rare issue with many-to-one mapping.
Imagine following relationship:
```yaml
Root:
  id: uuid, id
  children: one-to-many<Child>
Child:
  root: many-to-one<Root>, id, join column = root_id
  index: integer, id
  version: integer
```

I can persist root with children, but this is what happens when i persist child separately:
- `UnitOfWork.createEntity` is called, which extracts id through `IdentifierFlattener` as `[root: <uuid>, index: <integer>]`
- Application kicks in and does it's work
- `UnitOfWork.commit()` is called
- `BasicEntityPersister.update(entity)` is called
- `.updateTable` is successfully called, all ok here
- It tries to assign default version value to entity (why? it's update, not create) and **fetches id as `$this->em->getUnitOfWork()->getEntityIdentifier($entity)`, which is already flattened and contains root key instead of root_id** (BasicEntityPersister:369)
- it all boils down to `BasicEntityPersister.fetchVersionValue`, which calls `IdentifierFlattener.flattenIdentifier` again
- `.flattenIdentifier` is fed with already-flattened identifier, while it expects to find `root_id` in passed array so it throws an error

Doctrine version: v2.5.11 - this report may be already out-of-date
