### ISSUE TITLE
The command doctrine:schema:update doesn't see what field already MEDIUMTEXT

### ISSUE THREAD

**Issue by dmytroboiko** [doctrine/doctrine2#6824]
I have a field which I want to be mysql mediumtext
Example.orm.yaml
```
AppBundle\Entity\Example:
    type: entity
    table: example
    id:
        id:
            type: bigint
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        description:
            column: description
            type: string
            length: 1.5E6
```

Everything is fine, field created as 'mediumtext'
but whenever I run
php bin/console doctrine:schema:update --dump-sql

I get
ALTER TABLE table CHANGE description description MEDIUMTEXT NOT NULL;
though `description` is MEDIUMTEXT already.
