### ISSUE TITLE
[Doctrine\DBAL\Driver\PDOException] When using doctrine:database:create

### ISSUE THREAD

**Issue by GreyBlade** [doctrine/doctrine2#6908]
Hi, so im getting this errors when im trying to do doctrine:database:create on a composer generated project.
This are the errors.

```
[Doctrine\DBAL\Driver\PDOException]                                          
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name o  
  r service not known                                                          
                                                                               

                                                                               
  [PDOException]                                                               
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name o  
  r service not known                                                          
                                                                               

                                                                               
  [PDOException]                                                               
  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or s  
  ervice not known                                 
```
this is how my config.yml looks like:
```
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        server_version: 5.7
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
```

And my params.yml.dist looks like this:
```
parameters:
    database_host: localhost
    database_port: ~
    database_name: api_platform
    database_user: api_platform
    database_password: api_platform
    # You should uncomment this if you want use pdo_sqlite
    # database_path: '%kernel.project_dir%/data.db3'

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: ~
    mailer_password: ~
```

Any body can help me fix this issue?
Thanks #

**Comment by akovalyov** [comment]
@GreyBlade from your configs I presume, you're using Symfony and API Platform, right? Have you checked `parameters.yml` file instead of `parameters.yml.dist`? Have you tried to use `127.0.0.1` instead of localhost to force connection via TCP instead of socket? Which OS are you actually running? 
Btw, if you are trying to use Docker and Docker Compose shipped with API Platform, you should use `db` as a database_host.

Overall, this is not really a Doctrine issue but rather environment misconfiguration.

**Comment by GreyBlade** [comment]
Yes I am using api-platform, and i have changed parameters.yml and parameters.yml.dist with 127.0.0.1 and localhost but same error, I am using Ubuntu
This is my parameters.yml.dist
```
parameters:
    database_host: db
    database_port: 3306
    database_name: api_platform
    database_user: api_platform
    database_password: api_platform
    # You should uncomment this if you want use pdo_sqlite
    # database_path: '%kernel.project_dir%/data.db3'

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: ~
    mailer_password: ~
```

and paremeters.yml original form the api-platform configuration
```
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        server_version: 5.7
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
```
