### ISSUE TITLE
manyToMany findBy : No associative Table

### ISSUE THREAD

**Issue by GuigZ-** [doctrine/doctrine2#7071]
Hey,

When i try to user findBy with an association, sql throw an error.

Framework: SF 4
SQL : MariaDB

See my config:

```yml
App\Entity\Plant:
  type: entity
  manyToMany:
    concretes:
      targetEntity: Concrete
      inversedBy: plants
      joinTable:
        name: plant_concrete
        joinColumns:
          plant_id:
            referencedColumnName: id
        inverseJoinColumns:
          concrete_id:
            referencedColumnName: id
      cascade: ["persist", "remove"]
```
```yml
App\Entity\Concrete:
  type: entity
  manyToMany:
    plants:
      targetEntity: Plant
      mappedBy: concretes
      cascade: ['persist']
```

```php
$this->getDoctrine()->getRepository(Plant::class)->findBy(['concretes' => 'aaaaa']);
```

> (3/3) InvalidFieldNameException
> An exception occurred while executing 'SELECT t0.id AS id_1, t0.uuid AS uuid_2, t0.name AS name_3, t0.deleted AS deleted_4, t0.contact_mail AS contact_mail_5, t0.contact_last_name AS contact_last_name_6, t0.contact_first_name AS contact_first_name_7, t0.contact_phone AS contact_phone_8, t0.created_at AS created_at_9, t0.updated_at AS updated_at_10, t0.address_id AS address_id_11 FROM plant t0 WHERE plant_concrete.concrete_id = ?' with params ["aaaaa"]:
> 
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'plant_concrete.concrete_id' in 'where clause'

If you need more informations, i'm ok (:

BR.
GuigZ-
