### ISSUE TITLE
Undefined method BasicEntityPersister::getCacheRegion()

### ISSUE THREAD

**Issue by peter-gribanov** [doctrine/doctrine2#7174]
I catch a fatal error at [this](https://github.com/doctrine/doctrine2/blob/dfd9d1b9e7e260a5d0ea2fba2754a738cdd7135f/lib/Doctrine/ORM/Cache/Persister/Collection/AbstractCollectionPersister.php#L142) line:

> Call to undefined method Doctrine\ORM\Persisters\Entity\BasicEntityPersister::getCacheRegion()

Stack trace:

```
Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Doctrine\ORM\Persisters\Entity\BasicEntityPersister::getCacheRegion()
#31 vendor/doctrine/orm/lib/Doctrine/ORM/Cache/Persister/Collection/AbstractCollectionPersister.php(170): storeCollectionCache
#30 vendor/doctrine/orm/lib/Doctrine/ORM/Cache/Persister/Collection/NonStrictReadWriteCachedCollectionPersister.php(39): afterTransactionComplete
#29 vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(3353): Doctrine\ORM\{closure}
#28 vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(3380): performCallbackOnCachedPersister
#27 vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(3354): afterTransactionComplete
#26 vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(423): commit
#25 vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(358): flush
#24 var/cache/prod/ContainerXkna0tf/EntityManager_9a5be93.php(83): flush
...
```

Doctrine version:

```
$ composer show doctrine/*
doctrine/annotations                v1.6.0 Docblock Annotations Parser
doctrine/cache                      v1.7.1 Caching library offering an object-oriented API for many cache backends
doctrine/collections                v1.5.0 Collections Abstraction library
doctrine/common                     v2.8.1 Common Library for Doctrine projects
doctrine/dbal                       v2.6.3 Database Abstraction Layer
doctrine/doctrine-bundle            1.8.1  Symfony DoctrineBundle
doctrine/doctrine-cache-bundle      1.3.2  Symfony Bundle for Doctrine Cache
doctrine/doctrine-migrations-bundle v1.3.1 Symfony DoctrineMigrationsBundle
doctrine/inflector                  v1.3.0 Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator               1.1.0  A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                      v1.0.1 Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                 v1.6.2 Database Schema migrations using Doctrine DBAL
doctrine/orm                        v2.6.1 Object-Relational-Mapper for PHP
```

It's very likely that this is related to the second level cache.
I use [SncRedisBundle](https://github.com/snc/SncRedisBundle) for cache data in Redis.

Doctrine config:

```yml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:         'pdo_mysql'
                host:           '%env(MYSQL_HOST)%'
                port:           '%env(MYSQL_PORT)%'
                dbname:         '%env(MYSQL_DATABASE)%'
                user:           '%env(MYSQL_USER)%'
                password:       '%env(MYSQL_PASSWORD)%'
                server_version: '%env(MYSQL_VERSION)%'
                charset:        UTF8
                mapping_types:
                    enum: string
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                auto_mapping: true
                connection: default
                mappings:
                    # ...
                second_level_cache:
                    region_cache_driver:
                        type: service
                        id: second_level_cache
                    enabled: true
                    log_enabled: false
                    region_lifetime: 600
                    regions:
                        user__device:
                            lifetime: 3600
                            cache_driver:
                                type: service
                                id: second_level_cache
                        # ...
```

SncRedisBundle config:

```yml
snc_redis:
    clients:
        doctrine:
            type: predis
            alias: doctrine
            dsn: 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%/2'
            logging: false
        doctrine_metadata:
            type: predis
            alias: doctrine_metadata
            dsn: 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%/%env(REDIS_DOCTRINE_METADATA_DB)%'
            logging: false
    doctrine:
        metadata_cache:
            client: doctrine_metadata
            entity_manager: default
            namespace: 'dmc:'
        result_cache:
            client: doctrine
            entity_manager: default
            namespace: 'drc:'
        query_cache:
            client: doctrine
            entity_manager: default
            namespace: 'dqc:'
        second_level_cache:
            client: doctrine
            entity_manager: default
            namespace: 'dslc:'
```

Region cache driver service:

```yml
services:
    second_level_cache:
        class: '%snc_redis.doctrine_cache_predis.class%'
        arguments: [ '@snc_redis.doctrine' ]
```

where `%snc_redis.doctrine_cache_predis.class%` equally `\Doctrine\Common\Cache\PredisCache`

Example entity configuration:

```php
/**
 * @ORM\Table(name="user_device")
 * @ORM\Entity()
 * @ORM\Cache(usage="NONSTRICT_READ_WRITE", region="user__device")
 */
class UserDevice
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="NONE")
     * @ORM\Cache(usage="NONSTRICT_READ_WRITE")
     * @ORM\ManyToOne(targetEntity="User", inversedBy="devices")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     * })
     *
     * @var User
     */
    private $user;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="NONE")
     * @ORM\Column(name="device_id", type="string", length=164, nullable=false)
     *
     * @var string
     */
    private $device_id = '';

   // ...

}
```
