### ISSUE TITLE
Autowire problem ?

### ISSUE THREAD

**Issue by public0** [doctrine/doctrine2#7183]
We decided to use work with YAML instead of Annotations and also not use autowire but instead register our services in services.yaml.

I made a custom query in a repo which i'm calling in a service which in turn is called in the controller.

Controller:
    ```
public function search($name)
    {
        $result = $this->tagService->search($name);
        var_dump($result);

        $response = [];
        return new ResponseService($response);
   }
```

TagService
```
    public function search($search)
    {
        try {
            return $this->entityManager->getRepository(Tag::class)->search($search);
        } catch (\Exception $e) {
            echo $e->getMessage();
        }
    }


```
TagRepository

```
class TagRepository extends ServiceEntityRepository
{
     public function __construct(RegistryInterface $registry)
     {
         parent::__construct($registry, Tag::class);
     }

    public function search($value)
    {
        return $this->createQueryBuilder('t')
            ->where('t.name LIKE :value')->setParameter('value', $value)
            ->orderBy('t.id', 'ASC')
            ->setMaxResults(10)
            ->getQuery()
            ->getResult()
        ;
    }
}

```

```
App\Entity\Tag:
    type: entity
    repositoryClass: App\Repository\TagRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:

        name:
            type: string
            length: 100

```
If my repo extends ServiceEntityRepository i get this where it says it can't find this service

The "App\Repository\TagRepository" entity repository implements "Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepositoryInterface", but its service could not be found. Make sure the service exists and is tagged with "doctrine.repository_service".

But if i extend EntityRepository instead of ServiceEntityRepository it works
