### ISSUE TITLE
Either sqlsrv is special or "doctrine: dbal: url:" breaks configurations.

### ISSUE THREAD

**Issue by Sluimers** [doctrine/doctrine2#7228]
### Bug Report

Symfony 4

|    Q        |   A
|------------ | ------
| BC Break    | As in does it break the app? yes.
| Version     | 2.6.1

#### Summary

the url setting in doctrine: dbal: url: somehow causes an override to the pdo_mysql driver with placeholder values.

#### Current behavior

It searches for pdo_mysql driver. 

![afbeelding](https://user-images.githubusercontent.com/235767/40187856-de62bf2c-59f8-11e8-8c54-3a17bd0731ac.png)

#### How to reproduce

doctrine.yaml
```
doctrine:
    dbal:
        driver: sqlsrv
        url: '%env(resolve:DATABASE_URL)%'
```

#### Expected behavior

SQLSTATE [IMSSP, -1]: Invalid option was passed to sqlsrv_connect.
