### ISSUE TITLE
Inheritance mapping: Entity has no field or association named username

### ISSUE THREAD

**Issue by BentCoder** [doctrine/doctrine2#7362]
|    Q        |   A
|------------ | -----
| Version     | 1.8.1

### Support Question

Just wondering if I am doing something wrong or missing. I am not able to write a query to pull data from child class when I use entity repository of the parent class. Is such thing possible? If not what the best way of doing this rather than injecting the entity repository of the child class?

I get error below:

```
[Semantical Error] line 0, col 54 near 'location = :': Error: Class AppBundle\\Entity\\Country has no field or association named username
```

Thanks

**ENTITY**

```
/**
 * @ORM\Entity
 * @ORM\Table(name="country")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="name", type="string")
 * @ORM\DiscriminatorMap({"uk"="Uk"})
 */
abstract class Country
{
    private $id;

    public function getId()
    {
        return $this->id;
    }
}

/**
 * @ORM\Entity
 */
class Uk extends Country
{
    private $location;

    public function getLocation()
    {
        return $this->id;
    }
}
```

**REPOSITORY**

```
app.entity_repository.country:
    class: Doctrine\ORM\EntityRepository
    factory: [ '@doctrine.orm.entity_manager', getRepository ]
    arguments:
        - AppBundle\Entity\Country

AppBundle\Repository\CountryRepository:
    arguments:
        $countryEntityRepository: '@app.entity_repository.country'
```

```
class CountryRepository
{
    private $countryEntityRepository;

    public function __construct(
        EntityRepository $countryEntityRepository
    ) {
        $this->countryEntityRepository = $countryEntityRepository;
    }

    public function findOneByLocation($location)
    {
        return $this->countryEntityRepository
            ->createQueryBuilder('c')
            ->where('c.location = :location')
            ->setParameters(['location' => $location])
            ->getQuery()
            ->getOneOrNullResult(Query::HYDRATE_SIMPLEOBJECT);
    }
}
```
