### ISSUE TITLE
One-To-One, Self-referencing with empty string

### ISSUE THREAD

**Issue by CuiKeng** [doctrine/doctrine2#7364]
|    Q        |   A
|------------ | -----
| Version     | 2.6.*

I am using One-To-One, Self-referencing, but my relation key is NOT NULL DEFAULT '', it seems not work for me.
```
class Category
{
    private $id;
    private $parent = '';
}
```
```
oneToOne:
        parent:
            targetEntity: Category
            joinColumn:
                name: parent_id
                referencedColumnName: id
```

When store top category It throw me an exception: 
Expected value of type "Category" for association field "Category#$parent", got "string" instead.
