### ISSUE TITLE
An exception occured in driver: MySQL server has gone away (Doctrine2, Typo3, Kubernetes, cloud sql proxy) 

### ISSUE THREAD

**Issue by cccdemon** [doctrine/doctrine2#7422]
**Proxy Service definition:** 

```yml
kind: Service
apiVersion: v1
metadata:
  name: {{CONTENT_INT_SVC}}
spec:
  selector:
    app: sql-proxy
  ports:
    - protocol: TCP
      port: {{MYSQL_PORT}}
      targetPort: {{CONTENT_INT_SVC}}

```
**Google Cloud Proxy Definition:** 
```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-proxy-deployment
  labels:
    app: sql-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sql-proxy
  template:
    metadata:
      labels:
        app: sql-proxy
    spec:
      containers:
      - name: sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.10
        command: ["/cloud_sql_proxy",
                  "-instances={{SUPPLIER_DB}}=tcp:0.0.0.0:{{SUPPLIER_INT_PORT}},{{ORDER_DB}}=tcp:0.0.0.0:{{ORDER_INT_PORT}},{{SHOP_MAIN_DB}}=tcp:0.0.0.0:{{SHOP_MAIN_INT_PORT}},{{CONTENT_DB}}=tcp:0.0.0.0:{{CONTENT_INT_PORT}},{{CD_ORDER_DB}}=tcp:0.0.0.0:{{CD_ORDER_INT_PORT}},{{FF_MASTER_DB}}=tcp:0.0.0.0:{{FF_MASTER_INT_PORT}},{{FOREIGN_DB}}=tcp:0.0.0.0:{{FOREIGN_INT_PORT}}",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
        ports:
          - name: {{ORDER_INT_SVC}}
            containerPort: {{ORDER_INT_PORT}}
          - name: {{SUPPLIER_INT_SVC}}
            containerPort: {{SUPPLIER_INT_PORT}}
          - name: {{CONTENT_INT_SVC}}
            containerPort: {{CONTENT_INT_PORT}}
          - name: {{CD_ORDER_INT_SVC}}
            containerPort: {{CD_ORDER_INT_PORT}}
          - name: {{SHOP_MAIN_INT_SVC}}
            containerPort: {{SHOP_MAIN_INT_PORT}}
          - name: {{FF_MASTER_INT_SVC}}
            containerPort: {{FF_MASTER_INT_PORT}}
          - name: {{FOREIGN_INT_SVC}}
            containerPort: {{FOREIGN_INT_PORT}}
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: service-account-order-db

```

**Exception:** 
```An exception occured in driver: MySQL server has gone away", Doctrine\DBAL\Driver\Mysqli\MysqliException)
```

After removing the Proxy and connecting direct to Google Cloud SQL, the connection will work properly.
It seems that 

```php
$this->_conn = $this->_driver->connect($this->_params, $user, $password, $driverOptions);
$this->_isConnected = true;`

```
does not returns the correct state (i dont know why) 

PHP Version: 7.1.22
Kubernetes Version 1.9.x
Google Managed Kubnernetes (Autoscaled - thats why we cant use fixed IPs for DB Access)

This issue is happens when you use TYPO3 CMS 8.7.19 on Google Kubernetes with SQL Proxy, install tool - Install tool: Database analyzer
