### ISSUE TITLE
Generated entities don't extend to the base class when we use inheritance mappings

### ISSUE THREAD

**Issue by maidmaid** [doctrine/doctrine2#7532]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6

#### Summary

When we run `doctrine:mapping:convert` with inheritance mappings, the generated entities don't extend to the base class.

#### Current behavior

From:

```yml
MyProject\Model\Person:
  type: entity
  inheritanceType: SINGLE_TABLE
  discriminatorColumn: { name: discr, type: string }
  discriminatorMap:
    person: Person
    employee: Employee
MyProject\Model\Employee:
  type: entity
```
Generated entity:

```php
class Employee {}
```

#### Expected behavior

```php
class Employee extends Person {}
```
