### ISSUE TITLE
Cascading removal oneToMany bidirectional + manyToMany

### ISSUE THREAD

**Issue by Nickolaus** [doctrine/doctrine2#9015]
Is it possible to execute a proper casade: remove action in this scenario (sorry for using yml):

EntityA <= should be deleted

```
EntityA
  oneToMany:
    bEntities:
      targetEntity: EntityB
      mappedBy: aEntity
      cascade: ["remove"]
  manyToMany:
    cEntities:
      targetEntity: EntityC
      cascade: ["remove"]
      joinTable:
        name: a_has_c
        joinColumns:
          a_id:
            referencedColumnName: id
        inverseJoinColumns:
          c_id:
            referencedColumnName: id
            onDelete: CASCADE

EntityB
  manyToOne:
    aEntity:
      targetEntity: EntityA
      inversedBy: bEntities
```

When I am trying to remove `EntityA` using the entity manager, the foreign key on `a_has_c` prevents the removal.
Doctrine executes a SQL delete statement of `EntityA` after all `bEntities` are removed but before the manyToMany entries are cascaded.
However if I have no `bEntities` referencing `EntityA` all `cEntities` and joinTable Entries are properly removed before `EntityA` is being removed.

Why is that the case, I had supposed that this logic would work, but I cannot understand why a deletion of `EntityA` is triggered after all `bEntities` have been removed.
I would have expected that the complete casacadation would happen before the actual entity to be removed would be deleted.

Can someone explain what doctrine is doing here, and how or if this is problem is solvable via doctrine configuration, or do I always have to remove all oneToMany entries from the owning side (EntityB) via code before actually removing the entity I actually want to remove (EntityA)
