### ISSUE TITLE
`doctrine:schema:create` does not respect `schema_filter`

### ISSUE THREAD

**Issue by simonberger** [doctrine/doctrine2#9627]
Version: 2.5.7

We configured some tables to be excluded from doctrine handling. This has bad effect on schema drop and schema create in tests which does not work as expected.

`doctrine:schema:drop` respects the tables we excluded via `schema_filter` regex configuration and does not remove them.
`doctrine:schema:create` on the other hand tries to create the not removed tables because it ignores the configuration.

Example configuration:

```yaml
doctrine:
  dbal:
    connections:
      default:
        schema_filter: ~^(?!(table1|table2))~
```

I looked in the code to get an idea. The two commands are structured very differently this made it also hard to decide in which library this issues should be created in. Let me know if I picked the wrong place at the end.
