### ISSUE TITLE
Multiple entity manager: The target entity specified on is unknown or not an entity

### ISSUE THREAD

**Issue by Lenny4** [doctrine/doctrine2#9666]
I have 2 entity managers:

```yml
# config/packages/doctrine.yaml
doctrine:
  dbal:
    default_connection: site
    connections:
      site:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_sqlsrv'
        # ...
      sage:
        url: '%env(resolve:DATABASE_URL_SAGE)%'
        driver: 'pdo_sqlsrv'
        # ...

  orm:
    auto_generate_proxy_classes: true
    default_entity_manager: site
    entity_managers:
      site:
        connection: site
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
          Site:
            is_bundle: false
            type: attribute
            dir: '%kernel.project_dir%/src/Entity/Site'
            prefix: 'App\Entity\Site'
            alias: Site
      sage:
        connection: sage
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
          Sage:
            is_bundle: false
            type: attribute
            dir: '%kernel.project_dir%/src/Entity/Sage'
            prefix: 'App\Entity\Sage'
            alias: Sage
```

I would like to create an entity which:
- has a `ManyToOne` relation with another entity managed by the same entity manager (`site`)
- has another `ManyToOne` relation with another entity managed by the `sage` entity manager

Something like this:
```php
// src/Entity/Site/CategoryFArticle.php
namespace App\Entity\Site;

use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]
class CategoryFArticle
{
    #[ORM\ManyToOne(targetEntity: 'App\Entity\Site\Category')]
    private $category;

    #[ORM\ManyToOne(targetEntity: 'App\Entity\Sage\FArticle')]
    private $fArticle;
}
```

The problem is when I do that I got the error:
```
Mapping
-------

 [FAIL] The entity-class App\Entity\Site\CategoryFArticle mapping is invalid:
 * The target entity 'App\Entity\Sage\FArticle' specified on App\Entity\Site\CategoryFArticle#fArticle is unknown or not an entity.


Database
--------


In MappingException.php line 23:
                                                                                                         
  The class 'App\Entity\Sage\FArticle' was not found in the chain configured namespaces App\Entity\Site  
                                                                                                         
```

Is that the intended behaviour ?

Thank you
