### ISSUE TITLE
OPCache wasted memory increases on each request

### ISSUE THREAD

**Issue by icedevelopment** [doctrine/doctrine2#9917]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.12.3

#### Summary

The OPCache wasted memory increases on each request if a paginator is used.

#### Current behavior

Whenever you make a request on a controller with a `Doctrine\ORM\Query` that uses [Doctrine\ORM\Tools\Pagination\Paginator#getIterator()](https://github.com/doctrine/orm/blob/c05e1709e9ffb9abe8d37260a78975cc816ee385/lib/Doctrine/ORM/Tools/Pagination/Paginator.php#L131), the DQL to SQL parser cache is redone each time.
Seems that this is bad a side effect introduced in commit https://github.com/doctrine/orm/pull/7865/commits/023e94661a1956215a6ddf17cb1b8908274b0d01 which was merged in [2.6.5](https://github.com/doctrine/orm/releases/tag/v2.6.5) so every version between this and [2.12.3](https://github.com/doctrine/orm/releases/tag/2.12.3) should be impacted.

#### How to reproduce

1. Install a Symfony app with Doctrine with the following standard cache configuration:

```yaml
# config/packages/prod/doctrine.yaml
doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system

```
2. Create a controller that uses a `Doctrine\ORM\Query` with a paginator (i.e. [knplabs/knp-paginator-bundle](https://packagist.org/packages/knplabs/knp-paginator-bundle)).

3. Set the environment to prod in .env (APP_ENV=prod and APP_DEBUG=0).

4. Make requests on the controller and watch `opcache_get_status()['memory_usage']['wasted_memory']` increase each time until OPCache is full and resets itself.

The expireQueryCache flag is always set to true here:

https://github.com/doctrine/orm/blob/c05e1709e9ffb9abe8d37260a78975cc816ee385/lib/Doctrine/ORM/Tools/Pagination/Paginator.php#L163

This makes Doctrine reparse the DQL each time:

https://github.com/doctrine/orm/blob/c05e1709e9ffb9abe8d37260a78975cc816ee385/lib/Doctrine/ORM/Query.php#L261-L272

Then Symfony will recreate the exact same file in its cache in `var/cache/prod/pools/`, invalidate and recompile it into OPCache:
https://github.com/symfony/cache/blob/7d8415956df68c8dcbc9468e119945e39bacead1/Adapter/PhpFilesAdapter.php#L254-L259

#### Expected behavior

The OPCache wasted_memory doesn't increase on each request.

**Comment by josephLaurent** [comment]
I got exactly the same issue, for me removing the following lines in the symfony config fix the issue:
```
doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool
```
Also, put this in the `php.ini` file prevent using the opcache and so fix the issue as well:
```
opcache.file_cache = NULL
opcache.file_cache_only = 0
```
But this are only quick fix that have impact on performances.
Is there any update on a possible fix on doctrine ?
